### ISSUE TITLE
Two indicator icons (Ubuntu 15.04)

### ISSUE THREAD

**Issue by Vlad-Online** [karas84/viberwrapper-indicator#10]
I have installed viberwrapper-indicator, but the main viber icon doesn't disappear. So I have two icons.

**Comment by karas84** [comment]
Did you install the one from this git or the one from webupd8's ppa?

**Comment by mhadjiantonis** [comment]
I have the same problem in Ubuntu 14.04.  I installed the one from webupd8 ppa.

**Comment by eingley** [comment]
I have ppa version of viberwrapper-indicator on Ubuntu 14.04 which was working fine until an update came through on the software updater 22 May.  Since then the icon on the top left corner of the screen has returned. Is there any possibility of another update through ppa to restore it as it was?

**Comment by karas84** [comment]
I'm not the one maintaining the PPA (which I think has been updated to one of the latest version) sorry. Either use the git version or ask @hotice for any PPA related question.

**Comment by eingley** [comment]
Thanks karas84.  An update came through the PPA today which has fixed it.

**Comment by karas84** [comment]
You are welcome.
