### ISSUE TITLE
"--close-chat" option fails

### ISSUE THREAD

**Issue by Sadi58** [karas84/viberwrapper-indicator#13]
I've just tried switching from PPA to git version, and I've got chat window open.
When I tried starting from terminal to see any error messages, all I've got was a dialog box asking to close terminal window.

**Comment by karas84** [comment]
I'll be needing more information. I can't seem to reproduce this at all.

**Comment by Sadi58** [comment]
Interesting... After trying a couple of times, the problem disappeared ;-)

**Comment by karas84** [comment]
You're welcome :)
