### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by kha0s178** [karas84/viberwrapper-indicator#14]
Clean just installed 14.04.2 LTS (updated and upgraded). 

$viberwrapper-indicator 
Using SYSTEM icons
Using NEW detection method
Launching Viber (/opt/viber/Viber) ... OK

But viber icon still in left corner.

**Comment by kha0s178** [comment]
Oh... one icon in left (violet) and one in right (gray)

**Comment by karas84** [comment]
Solved?

**Comment by kha0s178** [comment]
Yes. Thanx. First time got strange effect - double icon (in left and right
corners)
9 черв. 2015 15:40 "karas84" <notifications@github.com> пише:
