### ISSUE TITLE
Lock to launcher

### ISSUE THREAD

**Issue by michaeldg** [karas84/viberwrapper-indicator#15]
This tool works like a charm, thanks very much!

I'm new to Linux (desktop), can you provide a way to attach this to my launcher?

**Comment by karas84** [comment]
Thank you @michaeldg, there is a ppa that bundles a launcher with my code. You can get it [here](http://www.webupd8.org/2014/11/viber-wrapper-indicator-hides-floating.html?m=1). Follow the instructions and you'll be good :)
