### ISSUE TITLE
Viber needs to be activated prior to running viberwrapper-indicator

### ISSUE THREAD

**Issue by cascaval** [karas84/viberwrapper-indicator#3]
The program is working perfectly if Viber is already activated. However, if it is not and is run through viberwrapper-indicator, it's not possible to activate the account because Viber always self-terminates within less than 10 seconds.

It seems to be mandatory that Viber is first run directly, activated, terminated, and THEN run via viberwrapper-indicator. It's only a minor issue and if it cannot be fixed, it would be good to mention it in the readme.

System: Ubuntu 14.04

**Comment by karas84** [comment]
The last update should probably have taken care of the issue.

**Comment by karas84** [comment]
I'm closing this issue. If the proplem persists just ping me here.
