### ISSUE TITLE
Make the viber icon themable

### ISSUE THREAD

**Issue by bil-elmoussaoui** [karas84/viberwrapper-indicator#4]
Hello, 
i would like to ask you to make the viber icon themable by using the defaults folders for icons so we can change it so easily,

Thank you !!

**Comment by karas84** [comment]
Latest update asks the system first for icons (viber-normal and viber-notification) and defaults to builtin if both are not found.
I also made the icons for ubuntu dark/light and hicolor themes.

**Comment by bil-elmoussaoui** [comment]
Well, first of all  thank you for the fix. Just one thing, the icons must be in status folder, if you can do that too it's will be very nice! also, some distros uses 22x22 status icons instead of 24x24; you can check in the viber-wrapper python file if the distro uses 22 or 24 status icons and change the size.

**Comment by karas84** [comment]
@bil-elmoussaoui Thank you for your tips. I'm new to this icon stuff. Do you have some documentation about it? Why should I use the status folder (I thought it was just for system stuff like network and so on)? How can I check for the correct size? Feel free to link me some docs if you can, I'll gladly read it.

**Comment by bil-elmoussaoui** [comment]
You can take a look at my script here that i did to fix hardcoded tray indicator in ubuntu and other linux distro
[Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray)
You've to create 3 sizes for indicators that must be in status, the sizes are 16x16, 22x22 , 24x24. (i ever seen a linux distro that uses 16x16) but the must used are 22 and 24. 
For more informations take a look at this [GnomeArt](http://web.archive.org/web/20100305220150/http://live.gnome.org/GnomeArt/Tutorials/IconThemes)
