### ISSUE TITLE
High quality AppIndicator icon

### ISSUE THREAD

**Issue by s4nk** [karas84/viberwrapper-indicator#7]
It would be nice to replace the current notification area icon with a high quality one (the current icon looks a bit blurry). 

Otherwise this app is awesome, thanks a lot!

**Comment by ju5tify** [comment]
Agreed. Current icon is ugly

**Comment by umpirsky** [comment]
+1

**Comment by karas84** [comment]
I'd like to, too, but I lack any decent design skill XD. Any help would be appreciated.
For the time being I was thinking of letting the code ask the system for icons and use the default ones only if there are none installed by the user. This way, at least, anyone colud use its own icons.

**Comment by umpirsky** [comment]
@karas84 You can google for viber vector logo, I ound this one http://seeklogo.com/viber-vector-logo-248447.html. It can be tweaked.

Or, we can even ping [@viber](https://twitter.com/viber) to provide one.

**Comment by karas84** [comment]
Did some experiments and added icons for dark/light ubuntu theme so they better fit in. Follow the instructions in the README and let me know.

**Comment by umpirsky** [comment]
@karas84 Getting:

```
$ python viberwrapper-indicator.py 
Traceback (most recent call last):
  File "viberwrapper-indicator.py", line 536, in <module>
    viber_icons = ViberIcons.Instance()
  File "viberwrapper-indicator.py", line 140, in Instance
    cls.INSTANCE = ViberIcons()
  File "viberwrapper-indicator.py", line 112, in __init__
    ii_normal = git.lookup_icon('viber-normal', 24, 0).get_filename()
AttributeError: 'NoneType' object has no attribute 'get_filename'
```

**Comment by karas84** [comment]
@umpirsky Thanks, I should have fixed that. Anyhow that also happened because you didn't install the icons. Could you try installing them (instructions are in the readme)? Let me know.

**Comment by umpirsky** [comment]
@karas84 I did install them, but I keep getting this error.

![24_036](https://cloud.githubusercontent.com/assets/208957/7831566/1b5a5b6e-0458-11e5-8943-b83dffe04979.png)

**Comment by karas84** [comment]
@umpirsky Did you also update the caches?

**Comment by umpirsky** [comment]
@karas84 Yep.

**Comment by karas84** [comment]
@umpirsky I'm just guessing here, try checking the permissions/ownership of the icons so they match the other icons', then update the cache again (with the --force option) and try to change the theme to another one and then go back to the Ambiance one. If that doesn't work either, I'll have to check when I'm back home. Besides, did the previous error go away at least?

**Comment by karas84** [comment]
@umpirsky Oh, another thing. Did you install only the dark theme icons or all of the 3 themes? Since gtk only checks (apparently) the hicolor one you actually need to install them all.

**Comment by umpirsky** [comment]
@karas84 I guess anyone can read:

![selection_038](https://cloud.githubusercontent.com/assets/208957/7832381/e5300fdc-045e-11e5-946b-932e01f196a4.png)

I tried force cache clear, theme change, no help.

I installed them all, but I noticed that folder structure is not same for [hicolor](https://github.com/karas84/viberwrapper-indicator/tree/master/icons/hicolor/96x96/apps) and [ubuntu-mono-dark](https://github.com/karas84/viberwrapper-indicator/tree/master/icons/ubuntu-mono-dark/apps/24). Is that on purpose?

**Comment by karas84** [comment]
@umpirsky Yes it is. I noticed that too. The hicolor  icons have a different structure, don't know why. Anyway that's strange, It's working nicely on my system, I'll have to do some experimenting on other clean machines. It would be also useful to have some feedback from other users to confirm this if possible.

**Comment by umpirsky** [comment]
@karas84 Thanks for investigating, if you need any more info from my end feel free to ping me.

**Comment by s4nk** [comment]
thanks @karas84, I'll test it too once I have some time, probably next week

**Comment by karas84** [comment]
@umpirsky I just tested the last git on a clean 14.04.2 install. This is what I did: installed dependencies and viber, merged icons, rebuilt caches (for each of the 3 folders and got the "Cache file created successfully" every time). Then I ran the script and the indicator found the right icons immediately, I even tried to change the theme (dark/light/other) and the icons changed accordingly.

**Comment by umpirsky** [comment]
@karas84 Must be something related to my system. I will try again. Would be cool to provide install script, that will copy icons and rebuild caches. Thanks.

**Comment by karas84** [comment]
@umpirsky There is a PPA maintained by @hotice that does this, so for now I'm not planning on that but rather I'll be focusing on bugs and so. For the time being I'm closing this issue. Feel free to post any other problem here if you still cannot manage to get it working.

**Comment by umpirsky** [comment]
@karas84 I know, thanks! Keep doing great job.

**Comment by umpirsky** [comment]
@karas84 Installing `ppa:nilarimogard/webupd8` did the trick. Strange, but it works.

**Comment by karas84** [comment]
Strange indeed. But I'm glad it's working.
