### ISSUE TITLE
Indicator doesn't work properly after update on Ubuntu 15.04

### ISSUE THREAD

**Issue by ant-** [karas84/viberwrapper-indicator#9]
I've update the system recently and notice a bug. When I run viberwrapper-indicator a stock system tray icon is still appear in a top left corner.
http://i.imgur.com/O1rON0v.jpg

**Comment by karas84** [comment]
Did you install the one from this git or the one from webupd8's ppa?

**Comment by lilo-chita** [comment]
Seems to be related.
After wrapper update a couple days ago it's broken. Looks exactly the same stock system tray icon is still appear in a top left corner.

Ubuntu 14.04 LTS 64bit
deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu trusty main

**Comment by karas84** [comment]
I'm not the one maintaining the ppa so I can't help you there, I'm sorry.

**Comment by ant-** [comment]
I've installed from the ppa too.
So, will try to use version from the git.

**Comment by hotice** [comment]
@ant- the version in the PPA is now the latest from git so you can simply update to the version from the PPA (make sure it's "git20150527" and not an older version).

**Comment by ant-** [comment]
@hotice yep, it is all okay now. Thank you.

**Comment by lilo-chita** [comment]
Seems to be OK now, thank you.

**Comment by karas84** [comment]
You are welcome. I'm closing the issue.
